[package]
name = "validate-npm-package-name"
version = "0.1.0"
authors = ["Chris Krycho <hello@chriskrycho.com>"]
edition = "2024"

[lib]

[dependencies]
once_cell = "1.21.3"
percent-encoding = "2.3.2"
regex = "1.12.2"
