on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    name: Acceptance Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Set up cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run tests
        run: |
          cargo test --all --features mock-network
      - name: Lint with clippy
        run: cargo clippy
      - name: Lint tests with clippy
        run: |
          cargo clippy --tests --features mock-network

  shell-tests:
    name: Shell Script Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        run: sudo npm install -g bats
      - name: Check out code
        uses: actions/checkout@v7
      - name: Run tests
        run: bats dev/unix/tests/

  validate-installer-checksum:
    name: Validate installer checksum
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Run check
        run: |
          cd dev/unix
          sha256sum --check SHASUMS256.txt
